version: '3.8'
services:
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD='Thang@123'
    ports:
      - '6379:6379'
    networks:
      - redis_network


networks:
  redis_network: